version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: java-logistics-db
    restart: always
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

volumes:
  postgres_data: